if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "Bundled GUI font is missing: ${INPUT}")
endif()
file(READ "${INPUT}" font_hex HEX)
if(font_hex STREQUAL "")
    message(FATAL_ERROR "Bundled GUI font is empty: ${INPUT}")
endif()
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1,\n" font_bytes "${font_hex}")
file(WRITE "${OUTPUT}" "/* Generated from assets/fonts/LiberationSans-Regular.ttf. */\nstatic const unsigned char gui_font_data[] = {${font_bytes}};\n")

if(NOT EXISTS "${INPUT_BOLD}")
    message(FATAL_ERROR "Bundled bold GUI font is missing: ${INPUT_BOLD}")
endif()
file(READ "${INPUT_BOLD}" font_hex HEX)
if(font_hex STREQUAL "")
    message(FATAL_ERROR "Bundled bold GUI font is empty")
endif()
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1,\n" font_bytes "${font_hex}")
file(APPEND "${OUTPUT}" "static const unsigned char gui_font_bold_data[] = {${font_bytes}};\n")
