foreach(browser IN ITEMS chromium firefox)
    set(dir "${ROOT}/browser/${browser}")
    file(READ "${dir}/manifest.json" manifest)
    string(JSON version ERROR_VARIABLE error GET "${manifest}" manifest_version)
    if(error OR NOT version EQUAL 3)
        message(FATAL_ERROR "Invalid MV3 manifest: ${dir}/manifest.json")
    endif()
    if(browser STREQUAL "chromium")
        set(script "service_worker.js")
        string(JSON declared ERROR_VARIABLE error GET "${manifest}" background service_worker)
    else()
        set(script "background.js")
        string(JSON declared ERROR_VARIABLE error GET "${manifest}" background scripts 0)
    endif()
    if(error OR NOT "${declared}" STREQUAL "${script}" OR
       NOT EXISTS "${dir}/${script}")
        message(FATAL_ERROR "Missing browser background script: ${dir}/${script}")
    endif()
endforeach()
