foreach(browser IN ITEMS chromium firefox)
    set(dir "${ROOT}/browser/${browser}")
    file(READ "${dir}/manifest.json" manifest)
    string(JSON version ERROR_VARIABLE error GET "${manifest}" manifest_version)
    if(error OR NOT version EQUAL 3)
        message(FATAL_ERROR "Invalid MV3 manifest: ${dir}/manifest.json")
    endif()
    if(browser STREQUAL "chromium")
        set(script "service_worker.js")
        string(JSON declared ERROR_VARIABLE error GET "${manifest}" background service_worker)
    else()
        set(script "background.js")
        string(JSON declared ERROR_VARIABLE error GET "${manifest}" background scripts 1)
        string(JSON filters ERROR_VARIABLE filter_error GET "${manifest}" background scripts 0)
        if(filter_error OR NOT "${filters}" STREQUAL "filters.js")
            message(FATAL_ERROR "Missing browser filter script: ${dir}/filters.js")
        endif()
    endif()
    if(NOT EXISTS "${dir}/filters.js" OR NOT EXISTS "${dir}/options.js")
        message(FATAL_ERROR "Missing browser settings script: ${dir}")
    endif()
    if(error OR NOT "${declared}" STREQUAL "${script}" OR
       NOT EXISTS "${dir}/${script}")
        message(FATAL_ERROR "Missing browser background script: ${dir}/${script}")
    endif()
endforeach()
